### ISSUE TITLE
User menu displays may include consecutive separators

### ISSUE THREAD

**Issue by ansuz** [cryptpad/cryptpad#1402] opened 2024-02-02 11:52 UTC
### Description

Under certain configurations it is possible for the dropdown user menu to display two consecutive separators.

### Steps to reproduce

1. as an administrator, check the _Do not advertize crowdfunding campaigns_ checkbox on the admin panel's _Network_ tab
2. ensure that the instance does not have an active survey, configured via the admin panel's _Broadcast_ tab in the _Survey link_ field
3. navigate to `/drive/`
4. click the user admin menu in the top-right corner
5. observe that two consecutive separators are  displayed

![image](https://github.com/cryptpad/cryptpad/assets/1264398/961986ab-6397-4529-9735-0e844c2db9a0)

### Expected behavior

only one separator should be displayed between visible menu items

### Which operating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Mozilla Firefox

### Extensions

Private firefox tab with no active extensions

### Version

5.7.0

**Comment by yflory** [comment] 2024-02-07 11:32
Thanks for the report, this will be fixed in the next release!
The issue was caused by an incorrect selector due to the recent changes in the dropdowns for accessibility.
We also found another issue related to the "HTTP workers": `Env` was updated in these workers after 250ms but the server called back instantly after an admin decree, so the notification was sent too early to the users.

**Closed** 2024-04-05 11:02 UTC
Labels: Bug, Fixed in staging, Drive
